project:
  type: website

website:
  title: "European Soccer Wages"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: analysis.qmd
        text: Analysis
      - href: model.qmd
        text: Model
      - href: sources.qmd
        text: Sources
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true



