---
title: "analysis"
---

```{r}
# install necessary libraries
library(readxl)
library(tidyverse)
library(writexl)
library(stringr)
library(ggthemes)
library(plotly)
library(formattable)
library(DT)
library(ggplot2)
```

```{r}
# read the excel file as a csv
top5 <- read_excel("Top5Leagues_Payroll.xlsx")
```

```{r}
# create and save a tibble, where the first season is 2013 and selects teams of the top four and bottom three (top four usually Champions League qualification, bottom three relegationn)
b <- top5 |>
  select(-c("# Pl", "Weekly Wages", "% Estimated", "Squad (again)")) |>
  mutate(annual = str_extract(`Annual Wages`, "\\$[0-9,]+")) |>
  mutate(annual = as.numeric(gsub("[$,]", "", annual))) |>
  select(-`Annual Wages`) |>
  filter(Season >= 2013, Standing <= 4 | Standing >= 18) |>
  mutate(top = Standing <= 4) |>
  mutate(top = ifelse(top == TRUE, "Top 4", "Bottom 3")) 
```

```{r}
# create ggplot object, mapping top team and bottom teams in standing and their payrolls
c <- b |>
  ggplot(aes(x = Season, y = annual, color = top, text = paste("Season:", Season, "\n", 
                                                               "Payroll:", currency(annual), "\n",
                                                               "Standing:", Standing, "\n",
                                                               "Team:", Squad))) +
  geom_point(alpha = 0.5) +
  scale_y_continuous(labels = scales::dollar_format()) +
  scale_x_continuous(breaks = seq(2013, 2022, by = 1)) +
  labs(title = "Payroll of Top Four vs Bottom Three Teams in Each Season",
       subtitle = "The payroll gap of top from bottom has steadily increased",
       y = "Payroll",
       color = "") +
  theme_fivethirtyeight()
```

```{r}
# convert to interactive plot
c |>
  ggplotly(tooltip = "text") |>
  layout(title = list(font = list(family = "Arial")),
         legend = list(font = list(family = "Arial")),
         xlabel = list(font = list(family = "Arial")))
```

```{r}
# create data frame where I can extract payroll rank vs standing 
d <- top5 |>
  select("Season", "Rk", "Squad", "Annual Wages", "Standing") |>
  mutate(annual = str_extract(`Annual Wages`, "\\$[0-9,]+")) |>
  mutate(annual = as.numeric(gsub("[$,]", "", annual))) |>
  select(-`Annual Wages`) |>
  summarise(.by = Season, Rk = Rk, Squad = Squad, Standing = Standing, annual = annual, percent = annual/sum(annual))
```
```{r}
# create data frame to measure a team's performance relative to payroll rank, diff is difference between payroll rank and standing (+ is good)
differential <- top5 |>
  select(-c("# Pl", "Weekly Wages", "% Estimated", "Squad (again)")) |>
  mutate(annual = str_extract(`Annual Wages`, "\\$[0-9,]+")) |>
  mutate(annual = as.numeric(gsub("[$,]", "", annual))) |>
  select(-`Annual Wages`) |>
  mutate(diff = Rk - Standing) |>
  summarise(.by = Squad, total = sum(diff), years = n()) 
```


```{r}
# add rate column since not all teams appear in the data the same amount of times
diff_1 <- differential |>
  mutate(rate = total / years) |>
  arrange(desc(rate)) 

#create interactive data frame
diff_DT <- diff_1 |>
  datatable()
```




```{r}
diff_DT |>
  formatStyle(columns = names(diff_1), fontFamily = "Arial")
```

